#!/usr/bin/python
import smbus

bus = smbus.SMBus(1)

addresses = 0x20

register = 0x12 

data = [0x09,0x00, 0b00000000]

bus.write_i2c_block_data(addresses, register, data)

register = 0x13

bus.write_i2c_block_data(addresses, register, data)
 
